# Generated by Django 6.0.7 on 2026-07-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0002_notification_board_name_alter_notification_board_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("collaborator_added", "Collaborator added"),
                    ("list_created", "List created"),
                    ("list_updated", "List updated"),
                    ("list_deleted", "List deleted"),
                    ("note_created", "Note created"),
                    ("note_updated", "Note updated"),
                    ("note_deleted", "Note deleted"),
                    ("board_updated", "Board updated"),
                    ("board_deleted", "Board deleted"),
                ],
                max_length=40,
            ),
        ),
    ]
