# Generated by Django 6.0.7 on 2026-07-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0011_rename_boards_lists"),
        ("notifications", "0004_alter_notification_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="notes.list",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="notes.note",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("collaborator_added", "Collaborator added"),
                    ("collaborator_removed", "Collaborator removed"),
                    ("list_created", "List created"),
                    ("list_updated", "List updated"),
                    ("list_deleted", "List deleted"),
                    ("note_created", "Note created"),
                    ("note_updated", "Note updated"),
                    ("note_completed", "Note completed"),
                    ("note_deleted", "Note deleted"),
                    ("board_updated", "Board updated"),
                    ("board_deleted", "Board deleted"),
                ],
                max_length=40,
            ),
        ),
    ]
