# Generated by Django 5.2 on 2025-06-24 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="todo_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note",
                to="notes.todolist",
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="notes",
            field=models.ManyToManyField(
                blank=True, related_name="todolist_notes", to="notes.note"
            ),
        ),
    ]
