# Generated by Django 5.2 on 2025-05-03 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_remove_todi_collaborators_remove_todi_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"verbose_name": "Note", "verbose_name_plural": "Notes"},
        ),
        migrations.AlterModelOptions(
            name="todolist",
            options={"verbose_name": "Todo List", "verbose_name_plural": "Todo Lists"},
        ),
        migrations.AlterModelOptions(
            name="todolistview",
            options={
                "verbose_name": "Todo List View",
                "verbose_name_plural": "Todo List Views",
            },
        ),
    ]
