# Generated by Django 5.2.8 on 2026-01-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0004_alter_workspace_created_by_alter_workspace_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="todo_list",
        ),
        migrations.AlterField(
            model_name="todolist",
            name="notes",
            field=models.ManyToManyField(
                blank=True, related_name="todolists", to="notes.note"
            ),
        ),
    ]
