# Generated by Django 5.2.10 on 2026-02-10

import django.db.models.deletion
from django.db import migrations, models


def backfill_note_workspace(apps, schema_editor):
    Note = apps.get_model("notes", "Note")
    TodoList = apps.get_model("notes", "TodoList")
    Workspace = apps.get_model("notes", "Workspace")

    db_alias = schema_editor.connection.alias
    through = TodoList.notes.through

    for note in Note.objects.using(db_alias).all().iterator():
        # Prefer deriving the workspace from existing todo list links.
        workspace_ids = list(
            TodoList.objects.using(db_alias)
            .filter(notes__id=note.id)
            .values_list("workspace_id", flat=True)
            .distinct()
        )

        if len(workspace_ids) == 1:
            workspace_id = workspace_ids[0]
        elif len(workspace_ids) == 0:
            # Notes without lists still must belong to a workspace. Fall back to the
            # owner's first workspace, creating one if needed.
            ws = (
                Workspace.objects.using(db_alias)
                .filter(owner_id=note.owner_id)
                .order_by("id")
                .first()
            )
            if ws is None:
                created_by_id = note.created_by_id or note.owner_id
                ws = Workspace.objects.using(db_alias).create(
                    name="My Workspace",
                    owner_id=note.owner_id,
                    created_by_id=created_by_id,
                )
            workspace_id = ws.id
        else:
            # Cross-workspace links are not supported. Keep the note in a single
            # workspace and drop links to todo lists in other workspaces.
            workspace_id = sorted(workspace_ids)[0]
            bad_todolist_ids = list(
                TodoList.objects.using(db_alias)
                .filter(notes__id=note.id)
                .exclude(workspace_id=workspace_id)
                .values_list("id", flat=True)
            )
            if bad_todolist_ids:
                through.objects.using(db_alias).filter(
                    todolist_id__in=bad_todolist_ids,
                    note_id=note.id,
                ).delete()

        Note.objects.using(db_alias).filter(id=note.id).update(workspace_id=workspace_id)


def noop_reverse(apps, schema_editor):
    # Intentionally no-op; we don't want to unset workspaces once assigned.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_remove_note_todo_list_alter_todolist_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="notes.workspace",
            ),
        ),
        migrations.RunPython(backfill_note_workspace, reverse_code=noop_reverse),
        migrations.AlterField(
            model_name="note",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="notes.workspace",
            ),
        ),
    ]

