# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_note_workspace_boundary"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="todolist",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="note",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name="workspace",
            options={
                "ordering": ["position", "created_at", "id"],
                "verbose_name": "Workspace",
                "verbose_name_plural": "Workspaces",
            },
        ),
        migrations.AlterModelOptions(
            name="todolist",
            options={
                "ordering": ["position", "created_at", "id"],
                "verbose_name": "Todo List",
                "verbose_name_plural": "Todo Lists",
            },
        ),
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["position", "created_at", "id"],
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
            },
        ),
    ]
