# Generated by Codex on 2026-06-30

from django.db import migrations, models
import django.db.models.deletion


def seed_note_positions(apps, schema_editor):
    TodoList = apps.get_model("notes", "TodoList")
    TodoListNotePosition = apps.get_model("notes", "TodoListNotePosition")

    positions = []
    for todo_list in TodoList.objects.all().order_by("id"):
        note_ids = list(
            todo_list.notes.all()
            .order_by("position", "created_at", "id")
            .values_list("id", flat=True)
        )
        positions.extend(
            TodoListNotePosition(
                todo_list_id=todo_list.id,
                note_id=note_id,
                position=index,
            )
            for index, note_id in enumerate(note_ids)
        )

    TodoListNotePosition.objects.bulk_create(positions, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_sort_positions"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoListNotePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo_list_positions",
                        to="notes.note",
                    ),
                ),
                (
                    "todo_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_positions",
                        to="notes.todolist",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="todolistnoteposition",
            constraint=models.UniqueConstraint(
                fields=("todo_list", "note"), name="unique_todolist_note_position"
            ),
        ),
        migrations.RunPython(seed_note_positions, migrations.RunPython.noop),
    ]
