# Generated by Django 5.2.10 on 2026-07-07 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0009_scoped_reordering"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="collaborators",
        ),
        migrations.RemoveField(
            model_name="note",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="todolist",
            name="collaborators",
        ),
        migrations.RemoveField(
            model_name="todolist",
            name="owner",
        ),
    ]
